version: 0.0
os: linux
files:
  - source: /
    destination: /home/frappe/codedeploy-artifacts/raplbaddi
hooks:
  AfterInstall:
    - location: scripts/deploy_router.py
      timeout: 600
      runas: frappe