from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

custom_fields = {
    "Purchase Order": [
        {
            "is_system_generated": 1,
            "label": "Branch",
            "fieldname": "branch",
            "insert_after": "company",
            "fieldtype": "Link",
            "default": "Real Appliances Private Limited",
            "options": "Branch",
            "reqd": 1,
            "allow_on_submit": 0,
        },
        {
            "is_system_generated": 1,
            "label": "Supplier Section Rapl",
            "fieldname": "supplier_section_rapl",
            "insert_after": "based_on_material_request",
            "fieldtype": "Section Break",
            "collapsible": 1,
            "print_hide": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Billing Rule",
            "fieldname": "billing_rule",
            "insert_after": "supplier_section_rapl",
            "fieldtype": "Link",
            "options": "Billing Rule Rapl",
            "no_copy": 0,
            "allow_on_submit": 1,
        },
        {
            "is_system_generated": 1,
            "fieldname": "supplier_section_clbrk1",
            "insert_after": "billing_rule",
            "fieldtype": "Column Break",
            "print_hide": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Is Billed",
            "fieldname": "is_billed",
            "insert_after": "supplier_section_clbrk1",
            "fieldtype": "Check",
            "default": "1",
            "allow_on_submit": 1,
        },
        {
            "is_system_generated": 1,
            "fieldname": "supplier_section_rapl_2",
            "insert_after": "is_billed",
            "fieldtype": "Section Break",
        },
        {
            "is_system_generated": 1,
            "label": "Remarks",
            "fieldname": "buying_remarks",
            "insert_after": "supplier_name",
            "fieldtype": "Small Text",
        },
    ],

    "Purchase Receipt": [
        {
            "is_system_generated": 1,
            "label": "Supplier Group",
            "fieldname": "supplier_group",
            "insert_after": "supplier_name",
            "fieldtype": "Link",
            "options": "Supplier Group",
            "fetch_from": "supplier.supplier_group",
            "read_only": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Transaction Type",
            "fieldname": "transaction_type_rapl",
            "insert_after": "column_break1",
            "fieldtype": "Link",
            "options": "Transaction Type",
            "read_only": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Branch",
            "fieldname": "branch",
            "insert_after": "company",
            "fieldtype": "Link",
            "default": "Real Appliances Private Limited",
            "options": "Branch",
            "reqd": 1,
            "allow_on_submit": 0,
        },
        {
            "is_system_generated": 1,
            "label": "Supplier Section Rapl",
            "fieldname": "supplier_section_rapl",
            "insert_after": "is_return",
            "fieldtype": "Section Break",
            "collapsible": 1,
            "print_hide": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Supplier Invoice No",
            "fieldname": "supplier_invoice_no",
            "insert_after": "supplier_section_rapl",
            "fieldtype": "Data",
            "mandatory_depends_on": "eval: doc.is_billed",
        },
        {
            "is_system_generated": 1,
            "label": "Billing Rule",
            "fieldname": "billing_rule",
            "insert_after": "supplier_invoice_no",
            "fieldtype": "Link",
            "options": "Billing Rule Rapl",
            "no_copy": 0,
            "allow_on_submit": 1,
        },
        {
            "is_system_generated": 1,
            "fieldname": "supplier_section_clbrk1",
            "insert_after": "billing_rule",
            "fieldtype": "Column Break",
            "print_hide": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Is Billed",
            "fieldname": "is_billed",
            "insert_after": "supplier_section_clbrk1",
            "fieldtype": "Check",
            "default": "1",
            "allow_on_submit": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Bill Attachment",
            "fieldname": "bill_attachment",
            "insert_after": "is_billed",
            "fieldtype": "Attach",
            "allow_on_submit": 1,
            "mandatory_depends_on": "eval: doc.is_billed",
        },
        {
            "is_system_generated": 1,
            "fieldname": "supplier_section_rapl_2",
            "insert_after": "bill_attachment",
            "fieldtype": "Section Break",
        },
        {
            "is_system_generated": 1,
            "label": "Remarks",
            "fieldname": "buying_remarks",
            "insert_after": "supplier_name",
            "fieldtype": "Small Text",
        },
        {
            "is_system_generated": 1,
            "label": "Internal Receipt",
            "fieldname": "internal_receipt",
            "insert_after": "is_return",
            "fieldtype": "Link",
            "options": "Stock Entry",
            "is_hidden": 1,
            "read_only": 1,
            "no_copy": 1,
            "reqd": 0,
            "allow_on_submit": 1,
        },
        {
            "is_system_generated": 1,
            "label": "Driver Number",
            "fieldname": "driver_number",
            "insert_after": "lr_date",
            "fieldtype": "Data",
            "reqd": 1,
            "allow_on_submit": 0,
        },
        {
            "is_system_generated": 1,
            "label": "Bilty/LR No",
            "fieldname": "bilty_no",
            "insert_after": "driver_number",
            "fieldtype": "Data",
            "reqd": 1,
            "allow_on_submit": 0,
        },
        {
            "is_system_generated": 1,
            "label": "Freight Status",
            "fieldname": "freight_status",
            "insert_after": "amount",
            "fieldtype": "Select",
            "default": "Already Paid by us",
            "options": "Already Paid by us\nPlease pay to Driver",
            "reqd": 1,
            "allow_on_submit": 0,
        },
        {
            "label": "Freight",
            "fieldname": "freight",
            "insert_after": "gst_vehicle_type",
            "fieldtype": "Table",
            "options": "Freight Table",
            "reqd": 1,
            "allow_on_submit": 1,
        },
        {
            "label": "Amount",
            "fieldname": "amount",
            "insert_after": "vehicle_no",
            "fieldtype": "Float",
            "default": "0",
            "reqd": 1,
            "allow_on_submit": 1,
        },
        {
            "label": "Vehicle No",
            "fieldname": "custom_vehicle_no",
            "insert_after": "gst_transporter_id",
            "fieldtype": "Link",
            "options": "Supplier",
            "reqd": 1,
        }
    ],

    "Material Request": [
        {
            "is_system_generated": 1,
            "label": "Remarks",
            "fieldname": "buying_remarks",
            "insert_after": "schedule_date",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
        }
    ],

    "Supplier Group": [
        {
            "is_system_generated": 1,
            "label": "Abbreviation",
            "fieldname": "abbreviation",
            "insert_after": "is_group",
            "fieldtype": "Data",
            "reqd": 1,
            "unique": 1,
        },
    ],
}

def execute():
    create_custom_fields(custom_fields)

    fields_to_hide = ["vehicle_no", "driver_name", "driver"]

    property_setters = [
        {
            "doctype": "Property Setter",
            "name": f"Purchase Receipt-{field}-hidden",
            "is_system_generated": 1,
            "doctype_or_field": "DocField",
            "module": "Raplbaddi",
            "doc_type": "Purchase Receipt",
            "field_name": field,
            "property": "hidden",
            "property_type": "Int",
            "value": "1",
        }
        for field in fields_to_hide
    ]
